---
- hosts: sonarqube
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: false
  tasks: 
  - name: Linux | RHEL YUM 
    yum: 
     name: "*"
     state: "latest"
    tags: 
    - updates  
    - rhel
  
  - name: Check for Python
    raw: test -e /usr/bin/python
    changed_when: false
    failed_when: false
    register: check_python

  - name: Install Python3
    raw: yum -y install python3
    when: check_python.rc != 0

  - name: pip self-update
    raw: yum -y install python3-pip
 
  - name: "install boto3"
    raw: pip3 install -U boto3

  - name: AWS | install awscli
    pip: name=awscli

  - name: :AWS | Assures dir exists
    file: path="~/.aws" state=directory

  - name: AWS | create credentials
    template:
      src: aws_credentials.tpl
      dest: "~/.aws/credentials"
  
